name: Lint
on:
  pull_request:
  push:
    branches:
      - main
    tags:
      - 'v*'
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.21.x
      - name: Analysis
        uses: golangci/golangci-lint-action@v3
        with:
          args: -v
          skip-pkg-cache: true
